version: "3.9"

services:
  identity:
    image: identity-service:latest
    container_name: identity-service
    ports:
      - "8001:8000"

  user:
    image: user-service:latest
    container_name: user-service
    ports:
      - "8002:8000"

  academic:
    image: academic-structure-service:latest
    container_name: academic-service
    ports:
      - "8003:8000"

  web:
    image: web:latest
    container_name: frontend-web
    ports:
      - "80:80"
