version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: uniforum-postgres
    environment:
      POSTGRES_USER: uniforum
      POSTGRES_PASSWORD: uniforum
      POSTGRES_DB: uniforum
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  identity-service:
    build: ../backend/services/identity-service
    container_name: identity-service
    ports:
      - "8001:8000"
    environment:
      DB_HOST: postgres
      DB_NAME: uniforum
      DB_USER: uniforum
      DB_PASSWORD: uniforum
    depends_on:
      - postgres

  user-service:
    build: ../backend/services/user-service
    container_name: user-service
    ports:
      - "8002:8000"
    environment:
      DB_HOST: postgres
      DB_NAME: uniforum
      DB_USER: uniforum
      DB_PASSWORD: uniforum
    depends_on:
      - postgres

  mongo:
    image: mongo:6
    container_name: uniforum-mongo
    ports:
      - "27017:27017"

  post-service:
    build: ../backend/services/post-service
    container_name: post-service
    ports:
      - "8004:8000"
    environment:
      MONGO_URI: mongodb://mongo:27017
    depends_on:
      - mongo

volumes:
  postgres_data:
