services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: uniforum
      POSTGRES_USER: uniforum
      POSTGRES_PASSWORD: uniforum
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
   image: redis:7
   container_name: redis
   ports:
    - "6379:6379"


  identity-service:
    build: ../backend/services/identity-service
    container_name: identity-service
    ports:
      - "8001:8000"
    environment:
      DB_HOST: postgres
      DB_NAME: uniforum
      DB_USER: uniforum
      DB_PASSWORD: uniforum
      JWT_SECRET: uniforum-secret-key
    depends_on:
      - postgres

  user-service:
    build: ../backend/services/user-service
    container_name: user-service
    ports:
      - "8002:8000"
    environment:
      DB_HOST: postgres
      DB_NAME: uniforum
      DB_USER: uniforum
      DB_PASSWORD: uniforum
      JWT_SECRET: uniforum-secret-key
    depends_on:
      - postgres

  forum-service:
    build: ../backend/services/forum-service
    container_name: forum-service
    ports:
      - "8003:8000"
    environment:
      DB_HOST: postgres
      DB_NAME: uniforum
      DB_USER: uniforum
      DB_PASSWORD: uniforum
      JWT_SECRET: uniforum-secret-key
    depends_on:
      - postgres

  post-service:
    build: ../backend/services/post-service
    container_name: post-service
    ports:
      - "8004:8000"
    environment:
      MONGO_URL: mongodb://mongo:27017
      MONGO_DB: postdb
      JWT_SECRET: uniforum-secret-key
    depends_on:
      - mongo

  reply-service:
    build: ../backend/services/reply-service
    container_name: reply-service
    ports:
      - "8005:8000"
    environment:
      MONGO_URL: mongodb://mongo:27017
      JWT_SECRET: uniforum-secret-key
    depends_on:
      - mongo

  academic-structure-service:
    build: ../backend/services/academic-structure-service
    container_name: academic-structure-service
    ports:
      - "8006:8000"
    environment:
      DB_HOST: postgres
      DB_NAME: uniforum
      DB_USER: uniforum
      DB_PASSWORD: uniforum
    depends_on:
      - postgres

  reaction-service:
   image: andyxalarcon/reaction-service:qa
   build: ../backend/services/reaction-service
   container_name: andyx-reaction-service
   ports:
    - "8007:8000"
   environment:
    REDIS_HOST: redis
    REDIS_PORT: 6379
   depends_on:
    - redis





volumes:
  postgres_data:
  mongo_data:
